### ISSUE TITLE
The project is lacking a LICENSE file

### ISSUE THREAD

**Issue by dov** [reinterpretcat/csharp-libs#7]
Please add a LICENSE file declaring your intended license.

Note that there is a derived TypeScript library that is licensed under the MIT license. Does this imply that this repository is licensed under MIT as well? Please clarify!

Thanks in advance!

**Comment by reinterpretcat** [comment]
Hi,

there is a license file: https://github.com/reinterpretcat/csharp-libs/blob/master/LICENSE

> Note that there is a derived TypeScript library

which library you refer to?

**Comment by dov** [comment]
Sorry. Thanks! I missed that file. (I don't know how I managed to do that. :-) )

The typescript library I referred to is at:

https://github.com/StrandedKitty/straight-skeleton
